services:
  db:
    image: postgres:15-alpine
    container_name: rpb-db-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rpb_password
      POSTGRES_DB: rpb_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data

volumes:
  postgres_data_local:
