services:
  db:
    image: postgres:17-alpine
    container_name: rpb-db-standalone
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rpb_password
      POSTGRES_DB: rpb_dashboard
    networks:
      - rpb-network
    volumes:
      - rpb-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  rpb-network:
    driver: bridge

volumes:
  rpb-db:
    external: true
