/**
 * Seed script for official Takara Tomy Beyblade X products
 * Data source: https://beyblade.takaratomy.co.jp/beyblade-x/lineup/
 */

import pg from 'pg'
import fs from 'fs'
import path from 'path'
import { PrismaClient } from '@/generated/prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'

const { Pool } = pg

// Initialize Prisma with PostgreSQL adapter
const connectionString = process.env.DATABASE_URL

if (!connectionString) {
  throw new Error('DATABASE_URL environment variable is required')
}

const pool = new Pool({ connectionString })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

// Load Hasbro Data
const hasbroDataPath = path.resolve(process.cwd(), 'data/cleaned/hasbro.json');
let hasbroData: { ttId: string, hasbroId: string, hasbroName: string }[] = [];

if (fs.existsSync(hasbroDataPath)) {
    hasbroData = JSON.parse(fs.readFileSync(hasbroDataPath, 'utf-8'));
}

const hasbroMap = new Map(hasbroData.map(h => [h.ttId, h]));

// Product data types
interface ProductData {
  code: string
  name: string
  nameEn?: string
  productType:
    | 'STARTER'
    | 'BOOSTER'
    | 'RANDOM_BOOSTER'
    | 'SET'
    | 'DOUBLE_STARTER'
    | 'TOOL'
    | 'COLOR_CHOICE'
  productLine: 'BX' | 'UX' | 'CX'
  price?: number
  releaseDate?: string
  isLimited?: boolean
  limitedNote?: string
  imageUrl?: string
  productUrl?: string
  shopUrl?: string
}

// Helper to parse date string (2025.3.29) to Date
function parseReleaseDate(dateStr?: string): Date | undefined {
  if (!dateStr) return undefined
  const parts = dateStr.split('.')
  if (parts.length !== 3) return undefined
  const [year, month, day] = parts.map(Number)
  if (year === undefined || month === undefined || day === undefined) return undefined
  return new Date(year, month - 1, day)
}

// Official product data from Takara Tomy website (scraped 2025)
const products: ProductData[] = [
  // === CX Line (Custom Line) ===
  {
    code: 'CX-00-DB',
    name: 'ドランブレイブS6-60V メタルコート:ブラック',
    productType: 'BOOSTER',
    productLine: 'CX',
    price: 1800,
    releaseDate: '2026.5.30',
    isLimited: true,
    limitedNote: 'タカラトミーモール・イベント限定',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BXG51_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx00-db.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810080572/',
  },
  {
    code: 'CX-11',
    name: 'エンペラーマイトデッキセット',
    productType: 'SET',
    productLine: 'CX',
    price: 5000,
    releaseDate: '2025.11.1',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX11_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx11.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810098775/',
  },
  {
    code: 'CX-10',
    name: 'ウルフハントF0-60DB',
    productType: 'BOOSTER',
    productLine: 'CX',
    price: 1700,
    releaseDate: '2025.11.1',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX10_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx10.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810097242/',
  },
  {
    code: 'CX-09',
    name: 'ソルエクリプスD5-70TK',
    productType: 'STARTER',
    productLine: 'CX',
    price: 2500,
    releaseDate: '2025.9.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX09_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx09.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810995678/',
  },
  {
    code: 'CX-08',
    name: 'ランダムブースターVol.7',
    productType: 'RANDOM_BOOSTER',
    productLine: 'CX',
    price: 1600,
    releaseDate: '2025.7.19',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX08_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx08.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810956983/',
  },
  {
    code: 'CX-07',
    name: 'ペガサスブラストATr',
    productType: 'STARTER',
    productLine: 'CX',
    price: 2600,
    releaseDate: '2025.7.19',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX07_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx07.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810956976/',
  },
  {
    code: 'CX-06',
    name: 'ランダムブースター フォックスブラッシュセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'CX',
    price: 1600,
    releaseDate: '2025.5.17',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX06_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx06.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810956969/',
  },
  {
    code: 'CX-05',
    name: 'ランダムブースターVol.6',
    productType: 'RANDOM_BOOSTER',
    productLine: 'CX',
    price: 1600,
    releaseDate: '2025.4.26',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX05_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx05.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939627/',
  },
  {
    code: 'CX-04',
    name: 'バトルエントリーセットC',
    productType: 'SET',
    productLine: 'CX',
    price: 6501,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX04_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx04.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939634/',
  },
  {
    code: 'CX-03',
    name: 'ペルセウスダークB6-80W',
    productType: 'BOOSTER',
    productLine: 'CX',
    price: 1600,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX03_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx03.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939610/',
  },
  {
    code: 'CX-02',
    name: 'ウィザードアークR4-55LO',
    productType: 'STARTER',
    productLine: 'CX',
    price: 2200,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX02_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx02.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939603/',
  },
  {
    code: 'CX-01',
    name: 'ドランブレイブS6-60V',
    productType: 'STARTER',
    productLine: 'CX',
    price: 2200,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/CX01_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/cx01.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939597/',
  },

  // === UX Line (Unique Line) ===
  {
    code: 'UX-00-AP',
    name: 'エアロペガサス3ｰ70A レッドVer.',
    productType: 'BOOSTER',
    productLine: 'UX',
    price: 1600,
    releaseDate: '2026.2.21',
    isLimited: true,
    limitedNote: 'アプリ・イベント限定',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BXG24_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux00-ap_red.html',
  },
  {
    code: 'UX-18',
    name: 'ランダムブースターVol.8',
    productType: 'RANDOM_BOOSTER',
    productLine: 'UX',
    price: 1600,
    releaseDate: '2025.12.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX18_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux18.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810097167/',
  },
  {
    code: 'UX-17',
    name: 'メテオドラグーン3-70J',
    productType: 'STARTER',
    productLine: 'UX',
    price: 2300,
    releaseDate: '2025.12.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX17_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux17.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810997627/',
  },
  {
    code: 'UX-16',
    name: 'ランダムブースター クロックミラージュセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'UX',
    price: 1400,
    releaseDate: '2025.10.11',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX16_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux16.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810990154/',
  },
  {
    code: 'UX-15',
    name: 'シャークスケイルデッキセット',
    productType: 'SET',
    productLine: 'UX',
    price: 4200,
    releaseDate: '2025.8.9',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX15_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux15.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810982432/',
  },
  {
    code: 'UX-14',
    name: 'スコーピオスピア0-70Z',
    productType: 'STARTER',
    productLine: 'UX',
    price: 2200,
    releaseDate: '2025.4.26',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX14_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux14.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810958499/',
  },
  {
    code: 'UX-13',
    name: 'ゴーレムロック1-60UN',
    productType: 'BOOSTER',
    productLine: 'UX',
    price: 1400,
    releaseDate: '2025.1.25',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX13_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux13.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939573/',
  },
  {
    code: 'UX-12',
    name: 'ランダムブースターVol.5',
    productType: 'RANDOM_BOOSTER',
    productLine: 'UX',
    price: 1400,
    releaseDate: '2024.12.28',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX12_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux12.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939566/',
  },
  {
    code: 'UX-11',
    name: 'インパクトドレイク9-60LR',
    productType: 'STARTER',
    productLine: 'UX',
    price: 2420,
    releaseDate: '2024.12.28',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX11_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux11.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939559/',
  },
  {
    code: 'UX-10',
    name: 'カスタマイズセットU',
    productType: 'SET',
    productLine: 'UX',
    price: 5700,
    releaseDate: '2024.11.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX10_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux10.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939542/',
  },
  {
    code: 'UX-09',
    name: 'サムライセイバー2-70L',
    productType: 'STARTER',
    productLine: 'UX',
    price: 3300,
    releaseDate: '2024.11.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX09_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux09.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939535/',
  },
  {
    code: 'UX-08',
    name: 'シルバーウルフ3-80FB',
    productType: 'STARTER',
    productLine: 'UX',
    price: 2080,
    releaseDate: '2024.10.12',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX08_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux08.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939498/',
  },
  {
    code: 'UX-07',
    name: 'フェニックスラダーデッキセット',
    productType: 'SET',
    productLine: 'UX',
    price: 4100,
    releaseDate: '2024.8.10',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX07_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux07.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914594/',
  },
  {
    code: 'UX-06',
    name: 'レオンクレスト7-60GN',
    productType: 'BOOSTER',
    productLine: 'UX',
    price: 1400,
    releaseDate: '2024.8.10',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX06_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux06.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914600/',
  },
  {
    code: 'UX-05',
    name: 'ランダムブースター シノビシャドウセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'UX',
    price: 1400,
    releaseDate: '2024.5.18',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX05_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux05.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914549/',
  },
  {
    code: 'UX-04',
    name: 'バトルエントリーセットU',
    productType: 'SET',
    productLine: 'UX',
    price: 6050,
    releaseDate: '2024.4.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX04_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux04.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914501/',
  },
  {
    code: 'UX-03',
    name: 'ウィザードロッド5-70DB',
    productType: 'BOOSTER',
    productLine: 'UX',
    price: 1400,
    releaseDate: '2024.3.30',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX03_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux03.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914495/',
  },
  {
    code: 'UX-02',
    name: 'ヘルズハンマー3-70H',
    productType: 'STARTER',
    productLine: 'UX',
    price: 1980,
    releaseDate: '2024.3.30',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX02_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux02.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914488/',
  },
  {
    code: 'UX-01',
    name: 'ドランバスター1-60A',
    productType: 'STARTER',
    productLine: 'UX',
    price: 1980,
    releaseDate: '2024.3.30',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/UX01_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/ux01.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914471/',
  },

  // === BX Line (Basic Line) ===
  {
    code: 'BX-00-DRGS',
    name: 'ドラグーンストーム4-60RA',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1700,
    releaseDate: '2025.12.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BXG22_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx00-drgs.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810099468/',
  },
  {
    code: 'BX-47',
    name: 'ストリングランチャーL レッドVer.',
    nameEn: 'String Launcher L Red Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 990,
    releaseDate: '2025.10.11',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX47_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx47.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810097396/',
  },
  {
    code: 'BX-46',
    name: 'バトルエントリーセット∞',
    nameEn: 'Battle Entry Set Infinity',
    productType: 'SET',
    productLine: 'BX',
    price: 7500,
    releaseDate: '2025.10.11',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX46_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx46.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810997610/',
  },
  {
    code: 'BX-45',
    name: 'サムライカリバー6-70M',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1500,
    releaseDate: '2025.8.9',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX45_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx45.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939580/',
  },
  {
    code: 'BX-44',
    name: 'トリケラプレスM-85BS',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1500,
    releaseDate: '2025.6.28',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX44_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx44.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939528/',
  },
  {
    code: 'BX-43',
    name: 'ギアケース ホワイトVer.',
    nameEn: 'Gear Case White Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 4000,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX43_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx43.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810958796/',
  },
  {
    code: 'BX-42',
    name: 'ラバーカスタムグリップ ブルーVer.',
    nameEn: 'Rubber Custom Grip Blue Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 1320,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX42_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx42.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810958536/',
  },
  {
    code: 'BX-41',
    name: 'ラバーカスタムグリップ ガンメタVer.',
    nameEn: 'Rubber Custom Grip Gunmetal Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 1320,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX41_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx41.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810958482/',
  },
  {
    code: 'BX-40',
    name: 'ワインダーランチャーL',
    nameEn: 'Winder Launcher L',
    productType: 'TOOL',
    productLine: 'BX',
    price: 880,
    releaseDate: '2025.3.29',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX40_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx40.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810958765/',
  },
  {
    code: 'BX-39',
    name: 'ランダムブースター シェルタードレイクセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2025.2.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX39_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx39.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939511/',
  },
  {
    code: 'BX-38',
    name: 'クリムゾンガルーダ4-70TP',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.11.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX38_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx38.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939504/',
  },
  {
    code: 'BX-37',
    name: 'ダブルエクストリームスタジアムセット',
    nameEn: 'Double Xtreme Stadium Set',
    productType: 'SET',
    productLine: 'BX',
    price: 8200,
    releaseDate: '2024.10.12',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX37_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx37.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810939481/',
  },
  {
    code: 'BX-36',
    name: 'ランダムブースター ホエールウェーブセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.9.14',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX36_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx36.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914617/',
  },
  {
    code: 'BX-35',
    name: 'ランダムブースターVol.4',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.7.13',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX35_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx35.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914570/',
  },
  {
    code: 'BX-34',
    name: 'コバルトドラグーン2-60C',
    productType: 'STARTER',
    productLine: 'BX',
    price: 2321,
    releaseDate: '2024.7.13',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX34_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx34.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914563/',
  },
  {
    code: 'BX-33',
    name: 'ヴァイスタイガー3-60U',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.6.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX33_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx33.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914556/',
  },
  {
    code: 'BX-32',
    name: 'ワイドエクストリームスタジアム',
    nameEn: 'Wide Xtreme Stadium',
    productType: 'TOOL',
    productLine: 'BX',
    price: 4400,
    releaseDate: '2024.7.13',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX32_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx32.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810926719/',
  },
  {
    code: 'BX-31',
    name: 'ランダムブースターVol.3',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.4.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX31_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx31.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914532/',
  },
  {
    code: 'BX-30',
    name: 'カスタムグリップ レッドVer.',
    nameEn: 'Custom Grip Red Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 1100,
    releaseDate: '2024.3.30',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX30_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx30.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810926702/',
  },
  {
    code: 'BX-29',
    name: 'カスタムグリップ ホワイトVer.',
    nameEn: 'Custom Grip White Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 1100,
    releaseDate: '2024.3.30',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX29_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx29.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914525/',
  },
  {
    code: 'BX-28',
    name: 'ストリングランチャー ホワイトVer.',
    nameEn: 'String Launcher White Ver.',
    productType: 'TOOL',
    productLine: 'BX',
    price: 990,
    releaseDate: '2024.3.30',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX28_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx28.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914518/',
  },
  {
    code: 'BX-27',
    name: 'ランダムブースター スフィンクスカウルセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.2.22',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX27_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx27.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913115/',
  },
  {
    code: 'BX-26',
    name: 'ユニコーンスティング5-60GP',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2024.1.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX26_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx26.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810914464/',
  },
  {
    code: 'BX-25',
    name: 'ギアケース',
    nameEn: 'Gear Case',
    productType: 'TOOL',
    productLine: 'BX',
    price: 4000,
    releaseDate: '2023.12.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX25_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx25.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913320/',
  },
  {
    code: 'BX-24',
    name: 'ランダムブースターVol.2',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.12.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX24_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx24.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913108/',
  },
  {
    code: 'BX-23',
    name: 'フェニックスウイング9-60GF',
    productType: 'STARTER',
    productLine: 'BX',
    price: 2420,
    releaseDate: '2023.12.27',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX23_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx23.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913092/',
  },
  {
    code: 'BX-22',
    name: 'ドランソード3-60F エントリーパッケージ',
    nameEn: 'Dran Sword 3-60F Entry Package',
    productType: 'STARTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.12.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX22_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx22.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913139/',
  },
  {
    code: 'BX-21',
    name: 'ヘルズチェインデッキセット',
    nameEn: 'Hells Chain Deck Set',
    productType: 'SET',
    productLine: 'BX',
    price: 3960,
    releaseDate: '2023.11.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX21_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx21.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913085/',
  },
  {
    code: 'BX-20',
    name: 'ドランダガーデッキセット',
    nameEn: 'Dran Dagger Deck Set',
    productType: 'SET',
    productLine: 'BX',
    price: 3960,
    releaseDate: '2023.11.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX20_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx20.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913078/',
  },
  {
    code: 'BX-19',
    name: 'ライノホーン3-80S',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.11.2',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX19_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx19.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913061/',
  },
  {
    code: 'BX-18',
    name: 'ストリングランチャー',
    nameEn: 'String Launcher',
    productType: 'TOOL',
    productLine: 'BX',
    price: 990,
    releaseDate: '2023.10.7',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX18_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx18.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913054/',
  },
  {
    code: 'BX-17',
    name: 'バトルエントリーセット',
    nameEn: 'Battle Entry Set',
    productType: 'SET',
    productLine: 'BX',
    price: 6050,
    releaseDate: '2023.10.7',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX17_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx17.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913047/',
  },
  {
    code: 'BX-16',
    name: 'ランダムブースター ヴァイパーテイルセレクト',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.10.7',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX16_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx16.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810912972/',
  },
  {
    code: 'BX-15',
    name: 'レオンクロー5-60P',
    productType: 'STARTER',
    productLine: 'BX',
    price: 1980,
    releaseDate: '2023.10.7',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX15_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx15.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810913030/',
  },
  {
    code: 'BX-14',
    name: 'ランダムブースターVol.1',
    productType: 'RANDOM_BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.9.9',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX14_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx14.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810912965/',
  },
  {
    code: 'BX-13',
    name: 'ナイトランス4-80HN',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.8.10',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX13_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx13.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910565/',
  },
  {
    code: 'BX-12',
    name: '3on3デッキケース',
    nameEn: '3on3 Deck Case',
    productType: 'TOOL',
    productLine: 'BX',
    price: 990,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX12_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx12.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910602/',
  },
  {
    code: 'BX-11',
    name: 'ランチャーグリップ',
    nameEn: 'Launcher Grip',
    productType: 'TOOL',
    productLine: 'BX',
    price: 700,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX11_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx11.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910787/',
  },
  {
    code: 'BX-10',
    name: 'エクストリームスタジアム',
    nameEn: 'Xtreme Stadium',
    productType: 'TOOL',
    productLine: 'BX',
    price: 2750,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX10_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx10.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910596/',
  },
  {
    code: 'BX-09',
    name: 'ベイバトルパス',
    nameEn: 'BeyBattle Pass',
    productType: 'TOOL',
    productLine: 'BX',
    price: 3300,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX09_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx09.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810905240/',
  },
  {
    code: 'BX-08',
    name: '3on3デッキセット',
    productType: 'SET',
    productLine: 'BX',
    price: 3960,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX08_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx08.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910572/',
  },
  {
    code: 'BX-07',
    name: 'スタートダッシュセット',
    productType: 'SET',
    productLine: 'BX',
    price: 5720,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX07_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx07.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910589/',
  },
  {
    code: 'BX-06',
    name: 'ナイトシールド3-80N',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX06_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx06.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910480/',
  },
  {
    code: 'BX-05',
    name: 'ウィザードアロー4-80B',
    productType: 'BOOSTER',
    productLine: 'BX',
    price: 1400,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX05_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx05.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910497/',
  },
  {
    code: 'BX-04',
    name: 'ナイトシールド3-80N',
    productType: 'STARTER',
    productLine: 'BX',
    price: 1980,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX04_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx04.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910404/',
  },
  {
    code: 'BX-03',
    name: 'ウィザードアロー4-80B',
    productType: 'STARTER',
    productLine: 'BX',
    price: 1980,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX03_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx03.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910473/',
  },
  {
    code: 'BX-02',
    name: 'ヘルズサイズ4-60T',
    productType: 'STARTER',
    productLine: 'BX',
    price: 1980,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX02_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx02.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910398/',
  },
  {
    code: 'BX-01',
    name: 'ドランソード3-60F',
    productType: 'STARTER',
    productLine: 'BX',
    price: 1980,
    releaseDate: '2023.7.15',
    imageUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/_image/BX01_list.png',
    productUrl: 'https://beyblade.takaratomy.co.jp/beyblade-x/lineup/bx01.html',
    shopUrl: 'https://takaratomymall.jp/shop/g/g4904810910381/',
  },
]

async function seedProducts() {
  console.log('🏭 Seeding Takara Tomy products...\n')

  let created = 0
  let updated = 0

  for (const product of products) {
    const hasbro = hasbroMap.get(product.code);

    const data = {
      code: product.code,
      name: product.name,
      productType: product.productType,
      productLine: product.productLine,
      price: product.price,
      releaseDate: parseReleaseDate(product.releaseDate),
      isLimited: product.isLimited ?? false,
      limitedNote: product.limitedNote,
      imageUrl: product.imageUrl,
      productUrl: product.productUrl,
      shopUrl: product.shopUrl,
      hasbroCode: hasbro?.hasbroId || null,
      nameHasbro: hasbro?.hasbroName || null,
    }

    const existing = await prisma.product.findUnique({
      where: { code: product.code },
    })

    if (existing) {
      await prisma.product.update({
        where: { code: product.code },
        data,
      })
      updated++
    } else {
      await prisma.product.create({ data })
      created++
    }
  }

  console.log(`✅ Products seeded: ${created} created, ${updated} updated`)
  console.log(`📦 Total products: ${products.length}`)

  // Summary by line
  const byLine = {
    BX: products.filter((p) => p.productLine === 'BX').length,
    UX: products.filter((p) => p.productLine === 'UX').length,
    CX: products.filter((p) => p.productLine === 'CX').length,
  }

  console.log(`\n📊 By product line:`)
  console.log(`   - BX (Basic): ${byLine.BX}`)
  console.log(`   - UX (Unique): ${byLine.UX}`)
  console.log(`   - CX (Custom): ${byLine.CX}`)
}

async function main() {
  try {
    await seedProducts()
  } catch (error) {
    console.error('❌ Error seeding products:', error)
    throw error
  } finally {
    await prisma.$disconnect()
    await pool.end()
  }
}

main()
