#!/usr/bin/env bun
/**
 * Generate `src/_entry-imports.generated.ts` with static imports for every
 * file under src/{events,commands,components}. Replaces the runtime glob
 * performed by `@discordx/importer`'s `importx()` — the bundler can see
 * these as static deps and include them in `bun build --compile` output.
 *
 * Run via `prebuild` hook. Output is gitignored.
 */
import { Glob } from 'bun';
import { resolve, relative } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SRC = resolve(ROOT, 'src');
const OUT = resolve(SRC, '_entry-imports.generated.ts');

const DIRS = ['events', 'commands', 'components'];
const EXT = new Set(['.ts', '.tsx']);

const imports: string[] = [];

for (const dir of DIRS) {
  const base = resolve(SRC, dir);
  const glob = new Glob('**/*.{ts,tsx}');
  for await (const rel of glob.scan({ cwd: base })) {
    // Skip declaration files, tests, and the generated file itself.
    if (rel.endsWith('.d.ts')) continue;
    if (rel.endsWith('.test.ts') || rel.endsWith('.spec.ts')) continue;
    const abs = resolve(base, rel);
    // Import path relative to the generated file in src/.
    const importPath = './' + relative(SRC, abs).replace(/\\/g, '/').replace(/\.tsx?$/, '.js');
    if (!EXT.has('.' + rel.split('.').pop())) continue;
    imports.push(importPath);
  }
}

imports.sort();

const body = `/* eslint-disable */
// AUTO-GENERATED by scripts/gen-entry-imports.ts — do NOT edit by hand.
// Ensures the bundler sees every @Discord/@Slash decorated module as a static
// dep so \`bun build --compile\` pulls them into the standalone binary.

${imports.map((p) => `import '${p}';`).join('\n')}
`;

await Bun.write(OUT, body);
console.log(`[gen-entry-imports] Wrote ${imports.length} imports → ${relative(ROOT, OUT)}`);
